# Generated by Django 5.2.12 on 2026-03-16 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'allen-kota'", unique=True)),
                ('api_key', models.CharField(db_index=True, help_text='Sent via X-API-Key or Authorization: Bearer header', max_length=64, unique=True)),
                ('external_tenant_id', models.CharField(blank=True, db_index=True, help_text='UUID from NestJS Tenant table — links this Institute to the apexiq-backend tenant', max_length=64, null=True, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_soft_cap', models.IntegerField(default=500000, help_text='Warn after this many tokens/day')),
                ('daily_hard_cap', models.IntegerField(default=1000000, help_text='Block after this many tokens/day')),
                ('max_concurrent_requests', models.IntegerField(default=10, help_text='Max parallel LLM calls for this tenant')),
                ('features_enabled', models.JSONField(blank=True, default=dict, help_text='e.g. {"feedback": true, "cheating": true, "batch": false}')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, unique=True)),
                ('institute_id_str', models.CharField(db_index=True, max_length=128)),
                ('feature', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='queued', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='ai_services.institute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id_str', models.CharField(db_index=True, help_text='Fallback string ID when Institute FK is not available', max_length=128)),
                ('feature', models.CharField(db_index=True, max_length=64)),
                ('model_used', models.CharField(max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='ai_services.institute')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institute_id_str', 'created_at'], name='ai_services_institu_e69a0f_idx'), models.Index(fields=['feature', 'created_at'], name='ai_services_feature_5cc700_idx')],
            },
        ),
    ]
