# Generated by Django 5.2.12 on 2026-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='vertical',
            field=models.CharField(choices=[('coaching', 'Coaching (JEE/NEET/Competitive)'), ('school', 'School (Class 1-12)')], db_index=True, default='coaching', help_text='Product vertical this tenant belongs to. Selects prompt/model variants. Can be overridden per-request via the X-Vertical header.', max_length=32),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='vertical',
            field=models.CharField(db_index=True, default='coaching', help_text='Vertical this call was served under (for per-vertical usage/billing breakdown)', max_length=32),
        ),
    ]
