# Generated by Django 5.2.12 on 2026-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_institute_vertical_usagelog_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Row is safe to delete after this time. Set on job creation.', null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_service_account',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this API key belongs to a trusted internal service (e.g. NestJS ai-bridge). Only service accounts may use X-Tenant-ID to operate on behalf of another tenant. Regular institute keys are NEVER allowed to impersonate another tenant.'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='institute_id_str',
            field=models.CharField(db_index=True, help_text='Denormalized slug — must match institute.slug. Used for fast filter queries.', max_length=128),
        ),
    ]
