# Generated by Django 5.2.12 on 2026-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_add_service_account_and_batch_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='board',
            field=models.CharField(choices=[('cbse', 'CBSE (NCERT)'), ('icse', 'ICSE / CISCE'), ('state', 'State Board')], db_index=True, default='cbse', help_text='Education board for a school tenant (CBSE / ICSE / State). Selects syllabus, textbook and paper-pattern framing. Usually supplied per-request via the X-Board header (the backend reads it from institutes.board); this is the fallback when the header is absent.', max_length=32),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='board',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Education board this call was served under (school tenants), for per-board usage breakdown', max_length=32),
        ),
    ]
