# Generated by Django 5.2.12 on 2026-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_institute_board_usagelog_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='board',
            field=models.CharField(choices=[('cbse', 'CBSE (NCERT)'), ('icse', 'ICSE / CISCE'), ('state', 'State Board'), ('ib', 'IB (International Baccalaureate)')], db_index=True, default='cbse', help_text='Education board for a school tenant (CBSE / ICSE / State). Selects syllabus, textbook and paper-pattern framing. Usually supplied per-request via the X-Board header (the backend reads it from institutes.board); this is the fallback when the header is absent.', max_length=32),
        ),
    ]
